### PR TITLE
mastodon: add iter.Seq API

### LINKED ISSUE #161: pagination not working for followers/following?
Hey there, thank you for making this SDK, I am making good use of it here: https://github.com/turbot/steampipe-plugin-mastodon

When I got to the followers/following part of the exercise, I wound up doing this workaround: https://github.com/turbot/steampipe-plugin-mastodon/blob/0bbcd2203aafcb4cb0a33b6f9b1d94567dbae600/mastodon/utils.go#L89 If that was unnecessary then please set me straight!

### PR DESCRIPTION
**Pull request by sbinet**
Fixes #161.

This CL properly handle pagination by separating the parsing of next/prev `Link` headers.
A zero-pagination value marks the end of pages.

This CL adds two examples of a `iter`-based APIs, simplifying the pagination handling in user code.

### CODE REVIEW

**Comment by sbinet** [comment]
@mattn PTAL.

not sure about what convention we should use for the naming of `iter`-based methods (that is, if we want to introduce such an API).

as for the `prev`/`next` pagination, I believe we currently don't properly allow for changing the pagination/iteration direction.

say:
`a)` start from beginning and follow the `next` links, vs
`b)` start from the end and follow the `prev` links.

I chose option `a)`.
if we want to support both iteration directions, we'll probably have to sophisticate a bit all of this.

**Comment by sbinet** [comment]
should I split it into 2 PRs ? (one with the pagination fix and another one with the `iter`-based API ?)

File: mastodon.go [hunk 1]
```diff
@@ -123,12 +124,15 @@ func (c *Client) doAPI(ctx context.Context, method string, uri string, params in
...
+		switch lh := resp.Header.Get("Link"); lh {
+		case "":
+			*pg = Pagination{}
+		default:
+			_, next, err := newPaginationPrevNext(lh)
 			if err != nil {
 				return err
 			}
-			*pg = *pg2
+			*pg = next
```
Comment (mattn) [inline mastodon.go:135]: I'm not sure but may be like following?
```
prev, next, err := newPaginationPrevNext(lh)
if err != nil {
    ...
}

if prev.SinceID != "" {
        next.SinceID = prev.SinceID
}
if prev.MinID != "" {
        next.MinID = prev.MinID
}
if next.Limit == 0 && prev.Limit != 0 {
        next.Limit = prev.Limit
}

*pg = next
```

Comment (sbinet) [reply mastodon.go:135]: I haven't checked in details, but I believe merging fields from the `prev` and `next` pages is what made page iterations problematic (as noted in #161, together with some of the proposed workarounds in that #161 issue).

when I was debugging this (and trying to come up with a minimal server implementation for the `TestAccountStatuses` test), I got the following responses from a mastodon instance:

```
<https://mamot.fr/api/v1/notifications?limit=80&max_id=23139138&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=23225860&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=23087388&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=23138613&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=23014087&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=23087344&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=22945639&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=23013930&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=22884109&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=22944624&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=22848268&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=22884064&types%5B%5D=follow>; rel="prev"
<https://mamot.fr/api/v1/notifications?limit=80&max_id=22790172&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=22847218&types%5B%5D=follow>; rel="prev"
[...]
```

applying your proposed changed leads to the iteration stopping after only one page:
```
<https://mamot.fr/api/v1/notifications?limit=80&max_id=23139138&types%5B%5D=follow>; rel="next", <https://mamot.fr/api/v1/notifications?limit=80&min_id=23225860&types%5B%5D=follow>; rel="prev"
```

so I think "my" proposal is better in that respect :)

Comment (mattn) [reply mastodon.go:135]: You're right. Thank you.

**Review by mattn — APPROVED** [review]

**Comment by sbinet** [comment]
I'd propose to tag this as `v0.0.11`.
what do you think ?

**Comment by mattn** [comment]
sure!
